### PR TITLE
Updated for XigmaNAS 12.*

### PR DESCRIPTION
**Pull request by Nivigor**
Fetching files with pkg fetch, not need exact file names. Work with all XigmaNAS 12, may be 13

### CODE REVIEW

**Comment by Nivigor** [comment]
Script independent to Xigmanas version

**Comment by Fox1911** [comment]
Don't work on XigmaNAS 13

**Comment by Nivigor** [comment]
_Don't work on XigmaNAS 13_
>
Succesfully tested on 13.1.0.5.9363 and 13.1.0.5.9725.
For tcsh shell use rehash command after install for update shell cache.

**Comment by ginggs** [comment]
Implemented in 3348a261afd4d7bcb5ff39ea1843d69ccfba7487

**Pull request closed without merging**
